-- TB_CONTRACT_INFO (계약내역) 테이블 생성 (Oracle 11g R2용)
-- ==========================================

CREATE TABLE TB_CONTRACT_INFO (
    CONTRACT_ID      NUMBER                NOT NULL, -- 계약 ID
    VENDORID         NUMBER                NOT NULL, -- 업체 ID (FK)
    CONTRACT_YEAR    NUMBER(4)             NOT NULL, -- 계약연도
    CONTRACT_START   DATE                  NOT NULL, -- 계약시작일
    CONTRACT_END     DATE                  NOT NULL, -- 계약종료일
    CONTRACT_YEARS   NUMBER(3),                      -- 계약기간(년수)
    CONTRACT_MONTHS  NUMBER(2),                      -- 계약기간(개월수)
    CONTRACT_TYPE    VARCHAR2(20)          NOT NULL, -- 구분 (유지보수/개발/라이센스/장비/도입/납품)
    CONTRACT_DESC    CLOB,                           -- 계약내역
    USEYN            CHAR(1)  DEFAULT 'Y'  NOT NULL, -- 사용여부
    REG_DATE         DATE     DEFAULT SYSDATE NOT NULL, -- 등록일
    REG_USERID       VARCHAR2(50)          NOT NULL, -- 등록자ID
    UPDATE_DATE      DATE,                           -- 수정일
    UPDATE_USERID    VARCHAR2(50),                   -- 수정자ID
    CONSTRAINT PK_TB_CONTRACT_INFO PRIMARY KEY (CONTRACT_ID)    
);

-- 시퀀스 생성 (CONTRACT_ID 자동 증가용)
CREATE SEQUENCE SEQ_TB_CONTRACT_INFO START WITH 1 INCREMENT BY 1;
-- 테이블 및 컬럼 주석 추가
COMMENT ON TABLE TB_CONTRACT_INFO IS '계약내역';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_ID IS '계약 ID';
COMMENT ON COLUMN TB_CONTRACT_INFO.VENDORID IS '업체 ID';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_YEAR IS '계약연도';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_START IS '계약시작일';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_END IS '계약종료일';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_YEARS IS '계약기간(년수)';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_MONTHS IS '계약기간(개월수)';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_TYPE IS '구분(유지보수/개발/라이센스/장비/도입/납품)';
COMMENT ON COLUMN TB_CONTRACT_INFO.CONTRACT_DESC IS '계약내역';
COMMENT ON COLUMN TB_CONTRACT_INFO.USEYN IS '사용여부';
COMMENT ON COLUMN TB_CONTRACT_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_CONTRACT_INFO.REG_USERID IS '등록자ID';
COMMENT ON COLUMN TB_CONTRACT_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_CONTRACT_INFO.UPDATE_USERID IS '수정자ID';