-- TB_VENDOR_INFO (벤더정보) 테이블 생성 (Oracle 11g R2용)
-- ==========================================

CREATE TABLE TB_VENDOR_INFO (
    VENDORID      NUMBER                NOT NULL, -- 업체 ID
    VENDOR_CODE   VARCHAR2(20)          NOT NULL, -- 업체 코드
    VENDOR_NAME   VARCHAR2(50)          NOT NULL, -- 업체명
    VENDOR_TYPE   VARCHAR2(100)         NOT NULL, -- 업체 구분
    BIZ_REG_NO    VARCHAR2(20),                   -- 사업자등록번호
    BIZ_TYPE      VARCHAR2(50),                   -- 업태
    BIZ_ITEM      VARCHAR2(50),                   -- 종목
    CEO_NAME      VARCHAR2(50),                   -- 대표차명
    TEL_NO        VARCHAR2(20),                   -- 대표전화번호
    EMAIL         VARCHAR2(100),                  -- 대표이메일
    ADDRESS       VARCHAR2(255),                  -- 회사주소
    MANAGER_NAME  VARCHAR2(50),                   -- 담당자명
    MANAGER_PHONE VARCHAR2(20),                   -- 담당자 연락처
    MANAGER_EMAIL VARCHAR2(100),                  -- 담당자 이메일
    STATUS        VARCHAR2(20),                   -- 거래상태
    REMARKS       CLOB,                           -- 비고
    USEYN         CHAR(1)      DEFAULT 'Y' NOT NULL, -- 사용여부
    REG_DATE      DATE         DEFAULT SYSDATE NOT NULL, -- 등록일
    REG_USERID    VARCHAR2(50)          NOT NULL, -- 등록자ID
    UPDATE_DATE   DATE,                           -- 수정일
    UPDATE_USERID VARCHAR2(50),                   -- 수정자ID
    CONSTRAINT PK_TB_VENDOR_INFO PRIMARY KEY (VENDORID)
);

-- 시퀀스 생성 (VENDORID 자동 증가용)
CREATE SEQUENCE SEQ_TB_VENDOR_INFO START WITH 1 INCREMENT BY 1;

-- 테이블 및 컬럼 주석 추가
COMMENT ON TABLE TB_VENDOR_INFO IS '벤더정보';
COMMENT ON COLUMN TB_VENDOR_INFO.VENDORID IS '업체 ID';
COMMENT ON COLUMN TB_VENDOR_INFO.VENDOR_CODE IS '업체 코드';
COMMENT ON COLUMN TB_VENDOR_INFO.VENDOR_NAME IS '업체명';
COMMENT ON COLUMN TB_VENDOR_INFO.VENDOR_TYPE IS '업체 구분';
COMMENT ON COLUMN TB_VENDOR_INFO.BIZ_REG_NO IS '사업자등록번호';
COMMENT ON COLUMN TB_VENDOR_INFO.BIZ_TYPE IS '업태';
COMMENT ON COLUMN TB_VENDOR_INFO.BIZ_ITEM IS '종목';
COMMENT ON COLUMN TB_VENDOR_INFO.CEO_NAME IS '대표차명';
COMMENT ON COLUMN TB_VENDOR_INFO.TEL_NO IS '대표전화번호';
COMMENT ON COLUMN TB_VENDOR_INFO.EMAIL IS '대표이메일';
COMMENT ON COLUMN TB_VENDOR_INFO.ADDRESS IS '회사주소';
COMMENT ON COLUMN TB_VENDOR_INFO.MANAGER_NAME IS '담당자명';
COMMENT ON COLUMN TB_VENDOR_INFO.MANAGER_PHONE IS '담당자 연락처';
COMMENT ON COLUMN TB_VENDOR_INFO.MANAGER_EMAIL IS '담당자 이메일';
COMMENT ON COLUMN TB_VENDOR_INFO.STATUS IS '거래상태';
COMMENT ON COLUMN TB_VENDOR_INFO.REMARKS IS '비고';
COMMENT ON COLUMN TB_VENDOR_INFO.USEYN IS '사용여부';
COMMENT ON COLUMN TB_VENDOR_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VENDOR_INFO.REG_USERID IS '등록자ID';
COMMENT ON COLUMN TB_VENDOR_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_VENDOR_INFO.UPDATE_USERID IS '수정자ID';
