-- CSRDEV.TB_CONTRACT_FILE definition

CREATE TABLE "CSRDEV"."TB_CONTRACT_FILE" 
   (	
   "FILEID" NUMBER NOT NULL ENABLE, 
	"CONTRACT_ID" NUMBER NOT NULL ENABLE,
	"UPLOAD_FILENAME" VARCHAR2(64) NOT NULL ENABLE, 
	"REAL_FILENAME" VARCHAR2(500) NOT NULL ENABLE, 
	"FILEPATH" VARCHAR2(200) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"REG_USERID" VARCHAR2(10) NOT NULL ENABLE, 
	"USEYN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "PK_TB_CONTRACT_FILE" PRIMARY KEY ("FILEID")  
   ) ;

CREATE SEQUENCE SEQ_CONTRACT_FILE START WITH 1 INCREMENT BY 1;

COMMENT ON TABLE CSRDEV.TB_CONTRACT_FILE IS '계약 첨부파일 테이블';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.FILEID IS '파일 ID';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.CONTRACT_ID IS '계약 ID';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.UPLOAD_FILENAME IS '서버에 저장하는 파일 명 ( 해시값 or 타입스탬프 기반 이름 )';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.REAL_FILENAME IS '파일명';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.FILEPATH IS '파일 저장 경로';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN CSRDEV.TB_CONTRACT_FILE.USEYN IS '사용여부';