CREATE TABLE public.TB_COR_INFO (
    CORCD VARCHAR(10) NOT NULL,
    CORNM VARCHAR(100),
    NATIONCD VARCHAR(10),
    COINCD VARCHAR(10),
    "LANGUAGE" VARCHAR(10),
    ACC_TITLE VARCHAR(10),
    CONSTRAINT PK_TB_COR_INFO PRIMARY KEY (CORCD)
);

COMMENT ON TABLE public.TB_COR_INFO IS '법인 정보 테이블';
COMMENT ON COLUMN public.TB_COR_INFO.CORCD IS '법인코드';
COMMENT ON COLUMN public.TB_COR_INFO.CORNM IS '법인명';
COMMENT ON COLUMN public.TB_COR_INFO.NATIONCD IS '국가코드';
COMMENT ON COLUMN public.TB_COR_INFO.COINCD IS '통화코드';
COMMENT ON COLUMN public.TB_COR_INFO."LANGUAGE" IS '언어코드';
COMMENT ON COLUMN public.TB_COR_INFO.ACC_TITLE IS '계정과목';
