-- TB_COMM_CODE Table (공통 코드 관리 테이블) for Supabase (PostgreSQL)

CREATE TABLE public.TB_COMM_CODE (
    CODEID          bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PARENTID        bigint          NOT NULL,
    NAME            varchar(10)     NOT NULL,
    VALUE           numeric,
    SORTORDER       integer,
    NOTE            varchar(1000),
    USEYN           varchar(1)      DEFAULT 'Y' NOT NULL,
    REG_DATE        timestamptz     DEFAULT now() NOT NULL,
    REG_USERID      varchar(10)     NOT NULL,
    UPDATE_DATE     timestamptz,
    UPDATE_USERID   varchar(10),
    CONSTRAINT PK_TB_COMM_CODE PRIMARY KEY (CODEID)
);

-- Comments
COMMENT ON TABLE public.TB_COMM_CODE IS '공통 코드 관리 테이블';

COMMENT ON COLUMN public.TB_COMM_CODE.CODEID IS '코드ID';
COMMENT ON COLUMN public.TB_COMM_CODE.PARENTID IS '부모코드 ID';
COMMENT ON COLUMN public.TB_COMM_CODE.NAME IS '이름';
COMMENT ON COLUMN public.TB_COMM_CODE.VALUE IS '값';
COMMENT ON COLUMN public.TB_COMM_CODE.SORTORDER IS '정렬순서';
COMMENT ON COLUMN public.TB_COMM_CODE.NOTE IS '설명';
COMMENT ON COLUMN public.TB_COMM_CODE.USEYN IS '사용여부';
COMMENT ON COLUMN public.TB_COMM_CODE.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_COMM_CODE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN public.TB_COMM_CODE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_COMM_CODE.UPDATE_USERID IS '수정자 ID';

-- Row Level Security (RLS)
ALTER TABLE public.TB_COMM_CODE ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all for authenticated users"
ON public.TB_COMM_CODE
FOR ALL
TO authenticated
USING (true);

CREATE POLICY "Enable read access for all users"
ON public.TB_COMM_CODE
FOR SELECT
USING (true);