CREATE TABLE public.TB_GROUP_MENU (
    GROUPID VARCHAR(10) NOT NULL,
    MENUID VARCHAR(40) NOT NULL,
    NOTE VARCHAR(2000),
    CONSTRAINT PK_TB_GROUP_MENU PRIMARY KEY (GROUPID, MENUID)
);

COMMENT ON TABLE public.TB_GROUP_MENU IS 'GROUP별 MENU 매핑 테이블';
COMMENT ON COLUMN public.TB_GROUP_MENU.GROUPID IS '그룹 ID';
COMMENT ON COLUMN public.TB_GROUP_MENU.MENUID IS '메뉴 ID';
COMMENT ON COLUMN public.TB_GROUP_MENU.NOTE IS '설명';
