-- TB_GROUP_INFO Table (GROUP 정보) for Supabase (PostgreSQL)

CREATE TABLE public.TB_GROUP_INFO (
    GROUPID     bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    SYSTEMCODE  varchar(20),
    GROUPNAME   varchar(50),
    GROUPNOTE   varchar(2000),
    CONSTRAINT PK_TB_GROUP_INFO PRIMARY KEY (GROUPID)
);

-- Comments
COMMENT ON TABLE public.TB_GROUP_INFO IS 'GROUP 정보 테이블';

COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPID IS '그룹 ID';
COMMENT ON COLUMN public.TB_GROUP_INFO.SYSTEMCODE IS '시스템 코드';
COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPNAME IS '그룹 이름';
COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPNOTE IS '그룹 설명';

-- Row Level Security (RLS)
ALTER TABLE public.TB_GROUP_INFO ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all for authenticated users"
ON public.TB_GROUP_INFO
FOR ALL
TO authenticated
USING (true);

CREATE POLICY "Enable read access for all users"
ON public.TB_GROUP_INFO
FOR SELECT
USING (true);