CREATE TABLE public.TB_GROUP_INFO (
    GROUPID NUMERIC NOT NULL,
    SYSTEMCODE VARCHAR(20),
    GROUPNAME VARCHAR(50),
    GROUPNOTE VARCHAR(2000),
    CONSTRAINT PK_TB_GROUP_INFO PRIMARY KEY (GROUPID)
);

COMMENT ON TABLE public.TB_GROUP_INFO IS 'GROUP 정보';
COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPID IS '그룹 ID';
COMMENT ON COLUMN public.TB_GROUP_INFO.SYSTEMCODE IS '시스템 코드';
COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPNAME IS '그룹 이름';
COMMENT ON COLUMN public.TB_GROUP_INFO.GROUPNOTE IS '그룹 설명';
