CREATE TABLE public.TB_MENU_INFO (
    MENUID VARCHAR(40) NOT NULL,
    SYSTEMCODE VARCHAR(10),
    MENUNAME VARCHAR(100),
    CONTROLLER VARCHAR(20),
    ACTION VARCHAR(20),
    URL VARCHAR(300),
    PARENTID VARCHAR(40),
    INFO VARCHAR(1000),
    SORT_ORDER NUMERIC,
    USEYN VARCHAR(1),
    CREATE_DATE TIMESTAMP WITH TIME ZONE,
    CREATE_USERID VARCHAR(10),
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USERID VARCHAR(10),
    CONSTRAINT PK_TB_MENU_INFO PRIMARY KEY (MENUID)
);

COMMENT ON TABLE public.TB_MENU_INFO IS 'MENU 정보';
COMMENT ON COLUMN public.TB_MENU_INFO.MENUID IS '메뉴 ID';
COMMENT ON COLUMN public.TB_MENU_INFO.SYSTEMCODE IS '시스템 코드';
COMMENT ON COLUMN public.TB_MENU_INFO.MENUNAME IS '메뉴 이름';
COMMENT ON COLUMN public.TB_MENU_INFO.CONTROLLER IS '메뉴 컨트롤러';
COMMENT ON COLUMN public.TB_MENU_INFO.ACTION IS '메뉴 행동';
COMMENT ON COLUMN public.TB_MENU_INFO.URL IS '메뉴 경로';
COMMENT ON COLUMN public.TB_MENU_INFO.PARENTID IS '상위 메뉴 ID';
COMMENT ON COLUMN public.TB_MENU_INFO.INFO IS '메뉴정보';
COMMENT ON COLUMN public.TB_MENU_INFO.SORT_ORDER IS '메뉴 정렬 순서';
COMMENT ON COLUMN public.TB_MENU_INFO.USEYN IS '사용 여부';
COMMENT ON COLUMN public.TB_MENU_INFO.CREATE_DATE IS '생성일';
COMMENT ON COLUMN public.TB_MENU_INFO.CREATE_USERID IS '생성자 ID';
COMMENT ON COLUMN public.TB_MENU_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_MENU_INFO.UPDATE_USERID IS '수정자 ID';
