CREATE TABLE public.TB_REQ_HIST (
    HISTROYID NUMERIC NOT NULL,
    REQID NUMERIC NOT NULL,
    REQENDDATE VARCHAR(10) NOT NULL,
    RESUSERID VARCHAR(10),
    DFCLTCD VARCHAR(10),
    MAN_DAY REAL,
    PROC_STATUS VARCHAR(10),
    PROC_RATE NUMERIC,
    ANSWER_HTML TEXT,
    ANSWER_TEXT TEXT,
    DELAYREASON_HTML TEXT,
    DELAYREASON_TEXT TEXT,
    REQHISTORY VARCHAR(1000),
    REG_DATE TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    REG_USERID VARCHAR(10) NOT NULL,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USERID VARCHAR(10),
    USEYN VARCHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_HIST PRIMARY KEY (HISTROYID)
);

COMMENT ON TABLE public.TB_REQ_HIST IS '요청사항 관리 테이블';
COMMENT ON COLUMN public.TB_REQ_HIST.HISTROYID IS '히스토리번호';
COMMENT ON COLUMN public.TB_REQ_HIST.REQID IS '요청번호';
COMMENT ON COLUMN public.TB_REQ_HIST.REQENDDATE IS '완료요청(예정)일';
COMMENT ON COLUMN public.TB_REQ_HIST.RESUSERID IS '조치자';
COMMENT ON COLUMN public.TB_REQ_HIST.DFCLTCD IS '난이도';
COMMENT ON COLUMN public.TB_REQ_HIST.MAN_DAY IS '투입공수';
COMMENT ON COLUMN public.TB_REQ_HIST.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN public.TB_REQ_HIST.PROC_RATE IS '진행률';
COMMENT ON COLUMN public.TB_REQ_HIST.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN public.TB_REQ_HIST.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN public.TB_REQ_HIST.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN public.TB_REQ_HIST.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN public.TB_REQ_HIST.REQHISTORY IS '조치내역(히스토리)';
COMMENT ON COLUMN public.TB_REQ_HIST.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_HIST.REG_USERID IS '등록자ID';
COMMENT ON COLUMN public.TB_REQ_HIST.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_REQ_HIST.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN public.TB_REQ_HIST.USEYN IS '삭제여부';
