CREATE TABLE public.TB_REQ_FILE (
    FILEID NUMERIC NOT NULL,
    REQID NUMERIC NOT NULL,
    REQTYPE VARCHAR(1) NOT NULL,
    "FILENAME" VARCHAR(1) NOT NULL,
    FILEPATH VARCHAR(1) NOT NULL,
    REG_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    REG_USERID VARCHAR(10) NOT NULL,
    USEYN VARCHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_FILE PRIMARY KEY (FILEID)
);

COMMENT ON TABLE public.TB_REQ_FILE IS '요청사항 첨부파일 테이블';
COMMENT ON COLUMN public.TB_REQ_FILE.FILEID IS '파일 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.REQ_ID IS '요청글 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.REQ_TYPE IS '첨부파일 구분';
COMMENT ON COLUMN public.TB_REQ_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN public.TB_REQ_FILE.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN public.TB_REQ_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_FILE.REG_USERID IS '등록자ID';
COMMENT ON COLUMN public.TB_REQ_FILE.USEYN IS '사용여부';
