-- TB_REQ_INFO Table (요청사항 관리) for Supabase (PostgreSQL)

CREATE TABLE public.TB_REQ_INFO (
    REQID           bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PARENTID        bigint,
    TITLE           varchar(50)     NOT NULL,
    CONTENTS_HTML   text,
    CONTENTS_TEXT   text,
    REQDATE         timestamptz     NOT NULL,
    DUEDATE         timestamptz,
    EXPECTDATE      timestamptz     NOT NULL,
    STARTDATE       timestamptz     NOT NULL,
    ENDDATE         timestamptz     NOT NULL,
    REQTYPE         varchar(10)     NOT NULL,
    SYSTEMCD        varchar(10)     NOT NULL,
    REQMENU         varchar(10),
    REQUSERID       varchar(10)     NOT NULL,
    RESUSERID       varchar(10),
    DFCLTCD         varchar(10),
    PRIORITYCD      varchar(10)     NOT NULL,
    MAN_DAY         real,
    PROC_STATUS     varchar(10),
    PROC_RATE       integer,
    ANSWER_HTML     text,
    ANSWER_TEXT     text,
    DELAYREASON_HTML text,
    DELAYREASON_TEXT text,
    CORCD           varchar(10)     NOT NULL,
    DEPTCD          varchar(10)     NOT NULL,
    OFFICECD        varchar(10)     NOT NULL,
    TEAMCD          varchar(10)     NOT NULL,
    REQHISTORY      varchar(1000),
    REG_DATE        timestamptz     DEFAULT now() NOT NULL,
    REG_USERID      varchar(10)     NOT NULL,
    UPDATE_DATE     timestamptz,
    UPDATE_USERID   varchar(10),
    USEYN           varchar(1)      DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_INFO PRIMARY KEY (REQID)
);

-- Comments
COMMENT ON TABLE public.TB_REQ_INFO IS '요청사항 관리 테이블';

COMMENT ON COLUMN public.TB_REQ_INFO.REQID IS '요청번호';
COMMENT ON COLUMN public.TB_REQ_INFO.PARENTID IS '상위요청번호';
COMMENT ON COLUMN public.TB_REQ_INFO.TITLE IS '제목';
COMMENT ON COLUMN public.TB_REQ_INFO.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN public.TB_REQ_INFO.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN public.TB_REQ_INFO.REQDATE IS '요청일';
COMMENT ON COLUMN public.TB_REQ_INFO.DUEDATE IS '처리기한';
COMMENT ON COLUMN public.TB_REQ_INFO.EXPECTDATE IS '완료예정일';
COMMENT ON COLUMN public.TB_REQ_INFO.STARTDATE IS '실제 시작일';
COMMENT ON COLUMN public.TB_REQ_INFO.ENDDATE IS '실제 종료일';
COMMENT ON COLUMN public.TB_REQ_INFO.REQTYPE IS '요청유형';
COMMENT ON COLUMN public.TB_REQ_INFO.SYSTEMCD IS '대상시스템';
COMMENT ON COLUMN public.TB_REQ_INFO.REQMENU IS '요청메뉴(영역)';
COMMENT ON COLUMN public.TB_REQ_INFO.REQUSERID IS '요청자';
COMMENT ON COLUMN public.TB_REQ_INFO.RESUSERID IS '조치자';
COMMENT ON COLUMN public.TB_REQ_INFO.DFCLTCD IS '난이도';
COMMENT ON COLUMN public.TB_REQ_INFO.PRIORITYCD IS '긴급도';
COMMENT ON COLUMN public.TB_REQ_INFO.MAN_DAY IS '투입공수';
COMMENT ON COLUMN public.TB_REQ_INFO.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN public.TB_REQ_INFO.PROC_RATE IS '진행률';
COMMENT ON COLUMN public.TB_REQ_INFO.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN public.TB_REQ_INFO.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN public.TB_REQ_INFO.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN public.TB_REQ_INFO.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN public.TB_REQ_INFO.CORCD IS '법인코드';
COMMENT ON COLUMN public.TB_REQ_INFO.DEPTCD IS '부서코드';
COMMENT ON COLUMN public.TB_REQ_INFO.OFFICECD IS '실 코드';
COMMENT ON COLUMN public.TB_REQ_INFO.TEAMCD IS '팀 코드';
COMMENT ON COLUMN public.TB_REQ_INFO.REQHISTORY IS '조치내역(히스토리)';
COMMENT ON COLUMN public.TB_REQ_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_INFO.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN public.TB_REQ_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_REQ_INFO.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN public.TB_REQ_INFO.USEYN IS '삭제여부';

-- Row Level Security (RLS)
ALTER TABLE public.TB_REQ_INFO ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all for authenticated users"
ON public.TB_REQ_INFO
FOR ALL
TO authenticated
USING (true);

CREATE POLICY "Enable read access for all users"
ON public.TB_REQ_INFO
FOR SELECT
USING (true);