CREATE TABLE public.TB_REQ_INFO (
    REQID NUMERIC NOT NULL,
    PARENTID NUMERIC,
    TITLE VARCHAR(50) NOT NULL,
    CONTENTS_HTML TEXT,
    CONTENTS_TEXT TEXT,
    REQDATE VARCHAR(10) NOT NULL,
    REQENDDATE VARCHAR(10),
    REQTYPE VARCHAR(10) NOT NULL,
    REQUSERID VARCHAR(10) NOT NULL,
    RESUSERID VARCHAR(10),
    DFCLTCD VARCHAR(10),
    PRIORITYCD VARCHAR(10) NOT NULL,
    MAN_DAY REAL,
    PROC_STATUS VARCHAR(10),
    PROC_RATE NUMERIC,
    ANSWER_HTML TEXT,
    ANSWER_TEXT TEXT,
    DELAYREASON_HTML TEXT,
    DELAYREASON_TEXT TEXT,
    CORCD VARCHAR(10) NOT NULL,
    DEPTCD VARCHAR(10) NOT NULL,
    TEAMCD VARCHAR(10) NOT NULL,
    REQHISTORY VARCHAR(1000),
    REG_DATE TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    REG_USERID VARCHAR(10) NOT NULL,
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USERID VARCHAR(10),
    USEYN VARCHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_TB_REQ_INFO PRIMARY KEY (REQID)
);

COMMENT ON TABLE public.TB_REQ_INFO IS '요청사항';
COMMENT ON COLUMN public.TB_REQ_INFO.REQID IS '요청번호';
COMMENT ON COLUMN public.TB_REQ_INFO.PARENTID IS '상위요청번호';
COMMENT ON COLUMN public.TB_REQ_INFO.TITLE IS '제목';
COMMENT ON COLUMN public.TB_REQ_INFO.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN public.TB_REQ_INFO.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN public.TB_REQ_INFO.REQDATE IS '요청일';
COMMENT ON COLUMN public.TB_REQ_INFO.REQENDDATE IS '완료요청(예정)일';
COMMENT ON COLUMN public.TB_REQ_INFO.REQTYPE IS '요청유형';
COMMENT ON COLUMN public.TB_REQ_INFO.REQUSERID IS '요청자';
COMMENT ON COLUMN public.TB_REQ_INFO.RESUSERID IS '조치자';
COMMENT ON COLUMN public.TB_REQ_INFO.DFCLTCD IS '난이도';
COMMENT ON COLUMN public.TB_REQ_INFO.PRIORITYCD IS '긴급도';
COMMENT ON COLUMN public.TB_REQ_INFO.MAN_DAY IS '투입공수';
COMMENT ON COLUMN public.TB_REQ_INFO.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN public.TB_REQ_INFO.PROC_RATE IS '진행률';
COMMENT ON COLUMN public.TB_REQ_INFO.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN public.TB_REQ_INFO.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN public.TB_REQ_INFO.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN public.TB_REQ_INFO.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN public.TB_REQ_INFO.CORCD IS '법인코드';
COMMENT ON COLUMN public.TB_REQ_INFO.DEPTCD IS '부서코드';
COMMENT ON COLUMN public.TB_REQ_INFO.TEAMCD IS '팀 코드';
COMMENT ON COLUMN public.TB_REQ_INFO.REQHISTORY IS '조치내역(히스토리)';
COMMENT ON COLUMN public.TB_REQ_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_INFO.REG_USERID IS '등록자ID';
COMMENT ON COLUMN public.TB_REQ_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_REQ_INFO.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN public.TB_REQ_INFO.USEYN IS '삭제여부';
