-- TB_REQ_FILE Table (요청사항 첨부파일 테이블) for Supabase (PostgreSQL)

CREATE TABLE public.TB_REQ_FILE (
    FILEID          bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    REQID           bigint          NOT NULL,
    HISTORYID       bigint          NOT NULL,
    REQTYPE         varchar(1)      NOT NULL,
    UPLOAD_FILENAME varchar(64)     NOT NULL,
    REAL_FILENAME   varchar(50)     NOT NULL,
    FILEPATH        varchar(100)    NOT NULL,
    REG_DATE        timestamptz     DEFAULT now() NOT NULL,
    REG_USERID      varchar(10)     NOT NULL,
    USEYN           varchar(1)      DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_FILE PRIMARY KEY (FILEID)
);

-- Comments
COMMENT ON TABLE public.TB_REQ_FILE IS '요청사항 첨부파일 테이블';

COMMENT ON COLUMN public.TB_REQ_FILE.FILEID IS '파일 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.REQID IS '요청글 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.HISTORYID IS '히스토리 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.REQTYPE IS '첨부파일 구분';
COMMENT ON COLUMN public.TB_REQ_FILE.UPLOAD_FILENAME IS '서버에 저장하는 파일 명 ( 해시값 or 타입스탬프 기반 이름 )';
COMMENT ON COLUMN public.TB_REQ_FILE.REAL_FILENAME IS '파일명';
COMMENT ON COLUMN public.TB_REQ_FILE.FILEPATH IS '파일 저장 경로';
COMMENT ON COLUMN public.TB_REQ_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_FILE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN public.TB_REQ_FILE.USEYN IS '사용여부';

-- Row Level Security (RLS)
ALTER TABLE public.TB_REQ_FILE ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all for authenticated users"
ON public.TB_REQ_FILE
FOR ALL
TO authenticated
USING (true);

CREATE POLICY "Enable read access for all users"
ON public.TB_REQ_FILE
FOR SELECT
USING (true);