-- TB_REQ_HIST Table (요청사항 관리 이력) for Supabase (PostgreSQL)

CREATE TABLE public.TB_REQ_HIST (
    HISTORYID       bigint          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    REQID           bigint          NOT NULL,
    PARENTID        bigint,
    TITLE           varchar(50)     NOT NULL,
    CONTENTS_HTML   text,
    CONTENTS_TEXT   text,
    REQDATE         varchar(10)     NOT NULL,
    REQENDDATE      varchar(10)     NOT NULL,
    REQTYPE         varchar(10)     NOT NULL,
    REQMENU         varchar(10),
    REQUSERID       varchar(10)     NOT NULL,
    RESUSERID       varchar(10),
    DFCLTCD         varchar(10),
    PRIORITYCD      varchar(10)     NOT NULL,
    MAN_DAY         real,
    PROC_STATUS     varchar(10),
    PROC_RATE       integer,
    ANSWER_HTML     text,
    ANSWER_TEXT     text,
    DELAYREASON_HTML text,
    DELAYREASON_TEXT text,
    CORCD           varchar(10)     NOT NULL,
    DEPTCD          varchar(10)     NOT NULL,
    TEAMCD          varchar(10)     NOT NULL,
    REQHISTORY      varchar(1000),
    REG_DATE        timestamptz     DEFAULT now() NOT NULL,
    REG_USERID      varchar(10)     NOT NULL,
    UPDATE_DATE     timestamptz, -- Added based on previous schema
    UPDATE_USERID   varchar(10), -- Added based on previous schema
    USEYN           varchar(1)      DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_HIST PRIMARY KEY (HISTORYID)
);

-- Comments
COMMENT ON TABLE public.TB_REQ_HIST IS '요청사항 관리 이력 테이블';

COMMENT ON COLUMN public.TB_REQ_HIST.HISTORYID IS '히스토리번호';
COMMENT ON COLUMN public.TB_REQ_HIST.REQID IS '요청번호';
COMMENT ON COLUMN public.TB_REQ_HIST.PARENTID IS '상위요청번호';
COMMENT ON COLUMN public.TB_REQ_HIST.TITLE IS '제목';
COMMENT ON COLUMN public.TB_REQ_HIST.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN public.TB_REQ_HIST.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN public.TB_REQ_HIST.REQDATE IS '요청일';
COMMENT ON COLUMN public.TB_REQ_HIST.REQENDDATE IS '완료요청(예정)일';
COMMENT ON COLUMN public.TB_REQ_HIST.REQTYPE IS '요청유형';
COMMENT ON COLUMN public.TB_REQ_HIST.REQMENU IS '요청메뉴(영역)';
COMMENT ON COLUMN public.TB_REQ_HIST.REQUSERID IS '요청자';
COMMENT ON COLUMN public.TB_REQ_HIST.RESUSERID IS '조치자';
COMMENT ON COLUMN public.TB_REQ_HIST.DFCLTCD IS '난이도';
COMMENT ON COLUMN public.TB_REQ_HIST.PRIORITYCD IS '긴급도';
COMMENT ON COLUMN public.TB_REQ_HIST.MAN_DAY IS '투입공수';
COMMENT ON COLUMN public.TB_REQ_HIST.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN public.TB_REQ_HIST.PROC_RATE IS '진행률';
COMMENT ON COLUMN public.TB_REQ_HIST.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN public.TB_REQ_HIST.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN public.TB_REQ_HIST.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN public.TB_REQ_HIST.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN public.TB_REQ_HIST.CORCD IS '법인코드';
COMMENT ON COLUMN public.TB_REQ_HIST.DEPTCD IS '부서코드';
COMMENT ON COLUMN public.TB_REQ_HIST.TEAMCD IS '팀 코드';
COMMENT ON COLUMN public.TB_REQ_HIST.REQHISTORY IS '조치내역(히스토리)';
COMMENT ON COLUMN public.TB_REQ_HIST.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_REQ_HIST.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN public.TB_REQ_HIST.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_REQ_HIST.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN public.TB_REQ_HIST.USEYN IS '삭제여부';

-- Row Level Security (RLS)
ALTER TABLE public.TB_REQ_HIST ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow all for authenticated users"
ON public.TB_REQ_HIST
FOR ALL
TO authenticated
USING (true);

CREATE POLICY "Enable read access for all users"
ON public.TB_REQ_HIST
FOR SELECT
USING (true);
