CREATE TABLE public.TB_USER_INFO (
    USERID VARCHAR(10) NOT NULL,
    USERPWD VARCHAR(100),
    USERNAME VARCHAR(100),
    EMPNO VARCHAR(10),
    DEPTCD VARCHAR(10),
    DEPTNAME VARCHAR(100),
    TEAMCD VARCHAR(10),
    TEAMNAME VARCHAR(100),
    CORCD VARCHAR(10),
    SYSCD VARCHAR(10),
    BIZCD VARCHAR(10),
    TELNO VARCHAR(20),
    MOB_PHONE_NO VARCHAR(20),
    EMAIL_ADDR VARCHAR(30),
    RETIRE_DATE VARCHAR(10),
    CORNAME VARCHAR(30),
    SYSNAME VARCHAR(30),
    BIZNAME VARCHAR(30),
    ADMIN_FLAG NUMERIC DEFAULT 0,
    CUSTCD VARCHAR(10),
    VENDCD VARCHAR(10),
    AUTH_FLAG NUMERIC DEFAULT 0,
    USER_DIV VARCHAR(10),
    PW_MISS_COUNT NUMERIC,
    REG_DATE TIMESTAMP WITH TIME ZONE,
    REG_USERID VARCHAR(10),
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USERID VARCHAR(10),
    CONSTRAINT PK_TB_USER_INFO PRIMARY KEY (USERID)
);

COMMENT ON TABLE public.TB_USER_INFO IS '유저 정보 테이블';
COMMENT ON COLUMN public.TB_USER_INFO.USERID IS '사용자 ID';
COMMENT ON COLUMN public.TB_USER_INFO.USERPWD IS '사용자 비밀번호';
COMMENT ON COLUMN public.TB_USER_INFO.USERNAME IS '사용자 이름';
COMMENT ON COLUMN public.TB_USER_INFO.EMPNO IS '사원 번호';
COMMENT ON COLUMN public.TB_USER_INFO.DEPTCD IS '부서 코드';
COMMENT ON COLUMN public.TB_USER_INFO.DEPTNAME IS '부서명';
COMMENT ON COLUMN public.TB_USER_INFO.TEAMCD IS '팀 코드';
COMMENT ON COLUMN public.TB_USER_INFO.TEAMNAME IS '팀명';
COMMENT ON COLUMN public.TB_USER_INFO.CORCD IS '법인 코드';
COMMENT ON COLUMN public.TB_USER_INFO.SYSCD IS '시스템 코드';
COMMENT ON COLUMN public.TB_USER_INFO.BIZCD IS '사업장 코드';
COMMENT ON COLUMN public.TB_USER_INFO.TELNO IS '전화 번호';
COMMENT ON COLUMN public.TB_USER_INFO.MOB_PHONE_NO IS '휴대폰 번호';
COMMENT ON COLUMN public.TB_USER_INFO.EMAIL_ADDR IS '전자메일 주소';
COMMENT ON COLUMN public.TB_USER_INFO.RETIRE_DATE IS '퇴사일';
COMMENT ON COLUMN public.TB_USER_INFO.CORNAME IS '법인코드명';
COMMENT ON COLUMN public.TB_USER_INFO.SYSNAME IS '시스템 코드명';
COMMENT ON COLUMN public.TB_USER_INFO.BIZNAME IS '사업장명';
COMMENT ON COLUMN public.TB_USER_INFO.ADMIN_FLAG IS '관리자권한';
COMMENT ON COLUMN public.TB_USER_INFO.CUSTCD IS '고객사 코드';
COMMENT ON COLUMN public.TB_USER_INFO.VENDCD IS '협력사 코드';
COMMENT ON COLUMN public.TB_USER_INFO.AUTH_FLAG IS '메뉴부여권한';
COMMENT ON COLUMN public.TB_USER_INFO.USER_DIV IS '사용자구분';
COMMENT ON COLUMN public.TB_USER_INFO.PW_MISS_COUNT IS '로그인 실패 횟수';
COMMENT ON COLUMN public.TB_USER_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN public.TB_USER_INFO.REG_USERID IS '등록자 id';
COMMENT ON COLUMN public.TB_USER_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN public.TB_USER_INFO.UPDATE_USERID IS '수정자 id';
