CREATE TABLE public.TB_USER_GROUP (
    USERID VARCHAR(10) NOT NULL,
    GROUPID VARCHAR(10) NOT NULL,
    CONSTRAINT PK_TB_USER_GROUP PRIMARY KEY (USERID, GROUPID)
);

COMMENT ON TABLE public.TB_USER_GROUP IS 'USER와 GROUP 매핑 테이블';
COMMENT ON COLUMN public.TB_USER_GROUP.USERID IS '사용자 ID';
COMMENT ON COLUMN public.TB_USER_GROUP.GROUPID IS '그룹 ID';
