CREATE OR REPLACE PROCEDURE CSRDEV.SP_REQ_CREATE_HISTORY (
    P_REQID             IN TB_REQ_HIST.REQID%TYPE,
    P_PARENTID          IN TB_REQ_HIST.PARENTID%TYPE,
    P_TITLE             IN TB_REQ_HIST.TITLE%TYPE,
    P_CONTENTS_HTML     IN CLOB,
    P_CONTENTS_TEXT     IN CLOB,
    P_REQDATE           IN TB_REQ_HIST.REQDATE%TYPE,
    P_DUEDATE           IN TB_REQ_HIST.DUEDATE%TYPE,
    P_EXPECTDATE        IN TB_REQ_HIST.EXPECTDATE%TYPE,
    P_STARTDATE         IN TB_REQ_HIST.STARTDATE%TYPE,
    P_ENDDATE           IN TB_REQ_HIST.ENDDATE%TYPE,
    P_REQTYPE           IN TB_REQ_HIST.REQTYPE%TYPE,
    P_SYSTEMCD          IN TB_REQ_HIST.SYSTEMCD%TYPE,
    P_REQMENU           IN TB_REQ_HIST.REQMENU%TYPE,
    P_REQMENU_ETC       IN TB_REQ_HIST.REQMENU_ETC%TYPE,
    P_REQTCODE			IN TB_REQ_HIST.REQTCODE%TYPE,
    P_RESTCODE			IN TB_REQ_HIST.RESTCODE%TYPE,
    P_BXTID             IN TB_REQ_HIST.BXTID%TYPE,
    P_REQUSERID         IN TB_REQ_HIST.REQUSERID%TYPE,
    P_RESUSERID         IN TB_REQ_HIST.RESUSERID%TYPE,
    P_IMPTCD            IN TB_REQ_HIST.IMPTCD%TYPE,
    P_DFCLTCD           IN TB_REQ_HIST.DFCLTCD%TYPE,
    P_PRIORITYCD        IN TB_REQ_HIST.PRIORITYCD%TYPE,
    P_MAN_DAY           IN TB_REQ_HIST.MAN_DAY%TYPE,
    P_PROC_STATUS       IN TB_REQ_HIST.PROC_STATUS%TYPE,
    P_PROC_RATE         IN TB_REQ_HIST.PROC_RATE%TYPE,
    P_ANSWER_HTML       IN CLOB,
    P_ANSWER_TEXT       IN CLOB,
    P_DELAYREASON_HTML  IN CLOB,
    P_DELAYREASON_TEXT  IN CLOB,
    P_CORCD             IN TB_REQ_HIST.CORCD%TYPE,
    P_DEPTCD            IN TB_REQ_HIST.DEPTCD%TYPE,
    P_OFFICECD          IN TB_REQ_HIST.OFFICECD%TYPE,
    P_TEAMCD            IN TB_REQ_HIST.TEAMCD%TYPE,
    P_NOTE_HTML         IN CLOB,
    P_NOTE_TEXT         IN CLOB,
    P_REG_USERID        IN TB_REQ_HIST.REG_USERID%TYPE,
    P_HISTORY_REASON    IN TB_REQ_HIST.HISTORY_REASON%TYPE,
    P_NEW_HISTORYID     OUT TB_REQ_HIST.HISTORYID%TYPE
)
IS
BEGIN
    INSERT INTO TB_REQ_HIST (
        HISTORYID, REQID, PARENTID, TITLE, CONTENTS_HTML, CONTENTS_TEXT, REQDATE, DUEDATE, EXPECTDATE, STARTDATE, ENDDATE,
        REQTYPE, SYSTEMCD, REQMENU, REQMENU_ETC, BXTID, REQUSERID, RESUSERID, IMPTCD, DFCLTCD, PRIORITYCD, MAN_DAY,
        PROC_STATUS, PROC_RATE, ANSWER_HTML, ANSWER_TEXT, DELAYREASON_HTML, DELAYREASON_TEXT, CORCD, DEPTCD, OFFICECD,
        TEAMCD, NOTE_HTML, NOTE_TEXT, REG_DATE, REG_USERID, USEYN, HISTORY_REASON
    )
    VALUES (
        SEQ_REQ_HIST.NEXTVAL, P_REQID, P_PARENTID, P_TITLE, P_CONTENTS_HTML, P_CONTENTS_TEXT, P_REQDATE, P_DUEDATE, P_EXPECTDATE, P_STARTDATE, P_ENDDATE,
        P_REQTYPE, P_SYSTEMCD, P_REQMENU, P_REQMENU_ETC, P_BXTID, P_REQUSERID, P_RESUSERID, P_IMPTCD, P_DFCLTCD, P_PRIORITYCD, P_MAN_DAY,
        P_PROC_STATUS, P_PROC_RATE, P_ANSWER_HTML, P_ANSWER_TEXT, P_DELAYREASON_HTML, P_DELAYREASON_TEXT, P_CORCD, P_DEPTCD, P_OFFICECD,
        P_TEAMCD, P_NOTE_HTML, P_NOTE_TEXT, sysdate, P_REG_USERID, 'Y', P_HISTORY_REASON
    )
    RETURNING HISTORYID INTO P_NEW_HISTORYID;
END;
