CREATE OR REPLACE PROCEDURE SP_REQ_SAVE_DRAFT (
    P_REQID         IN TB_REQ_INFO.REQID%TYPE,
    P_BXTID         IN TB_REQ_INFO.BXTID%TYPE,
    P_IMPTCD        IN TB_REQ_INFO.IMPTCD%TYPE,
    P_DFCLTCD       IN TB_REQ_INFO.DFCLTCD%TYPE,
    P_MAN_DAY       IN TB_REQ_INFO.MAN_DAY%TYPE,
    P_PROC_STATUS   IN TB_REQ_INFO.PROC_STATUS%TYPE,
    P_UPDATE_USERID IN TB_REQ_INFO.UPDATE_USERID%TYPE,
    P_ANSWER_HTML   IN CLOB,
    P_NOTE_HTML     IN CLOB
)
IS
BEGIN
    UPDATE TB_REQ_INFO
    SET
        BXTID         = P_BXTID,
        IMPTCD        = P_IMPTCD,
        DFCLTCD       = P_DFCLTCD,
        MAN_DAY       = P_MAN_DAY,
        PROC_STATUS   = P_PROC_STATUS,
        ANSWER_HTML   = P_ANSWER_HTML,
        NOTE_HTML     = P_NOTE_HTML,
        UPDATE_DATE   = SYSDATE,
        UPDATE_USERID = P_UPDATE_USERID
    WHERE REQID = P_REQID;
END;
/
