CREATE OR REPLACE PROCEDURE SP_REQ_CREATE (
    P_PARENTID      IN TB_REQ_INFO.PARENTID%TYPE,
    P_TITLE         IN TB_REQ_INFO.TITLE%TYPE,
    P_CONTENTS_HTML IN CLOB,
    P_REQDATE       IN TB_REQ_INFO.REQDATE%TYPE,
    P_DUEDATE       IN TB_REQ_INFO.DUEDATE%TYPE,
    P_EXPECTDATE    IN TB_REQ_INFO.EXPECTDATE%TYPE,
    P_STARTDATE     IN TB_REQ_INFO.STARTDATE%TYPE,
    P_ENDDATE       IN TB_REQ_INFO.ENDDATE%TYPE,
    P_REQTYPE       IN TB_REQ_INFO.REQTYPE%TYPE,
    P_SYSTEMCD      IN TB_REQ_INFO.SYSTEMCD%TYPE,
    P_REQMENU       IN TB_REQ_INFO.REQMENU%TYPE,
    P_REQMENU_ETC   IN TB_REQ_INFO.REQMENU_ETC%TYPE,
    P_REQTCODE      IN TB_REQ_INFO.REQTCODE%TYPE,
    P_BXTID         IN TB_REQ_INFO.BXTID%TYPE,
    P_REQUSERID     IN TB_REQ_INFO.REQUSERID%TYPE,
    P_RESUSERID     IN TB_REQ_INFO.RESUSERID%TYPE,
    P_IMPTCD        IN TB_REQ_INFO.IMPTCD%TYPE,
    P_DFCLTCD       IN TB_REQ_INFO.DFCLTCD%TYPE,
    P_PRIORITYCD    IN TB_REQ_INFO.PRIORITYCD%TYPE,
    P_MAN_DAY       IN TB_REQ_INFO.MAN_DAY%TYPE,
    P_PROC_STATUS   IN TB_REQ_INFO.PROC_STATUS%TYPE,
    P_PROC_RATE     IN TB_REQ_INFO.PROC_RATE%TYPE,
    P_CORCD         IN TB_REQ_INFO.CORCD%TYPE,
    P_DEPTCD        IN TB_REQ_INFO.DEPTCD%TYPE,
    P_OFFICECD      IN TB_REQ_INFO.OFFICECD%TYPE,
    P_TEAMCD        IN TB_REQ_INFO.TEAMCD%TYPE,
    P_REG_USERID    IN TB_REQ_INFO.REG_USERID%TYPE,
    P_NEW_REQID     OUT TB_REQ_INFO.REQID%TYPE
)
IS
BEGIN
    INSERT INTO TB_REQ_INFO (
        REQID, PARENTID, TITLE, CONTENTS_HTML, REQDATE, DUEDATE, EXPECTDATE, STARTDATE, ENDDATE,
        REQTYPE, SYSTEMCD, REQMENU, REQMENU_ETC, REQTCODE, BXTID, REQUSERID, RESUSERID,
        IMPTCD, DFCLTCD, PRIORITYCD, MAN_DAY, PROC_STATUS, PROC_RATE, CORCD, DEPTCD, OFFICECD, TEAMCD,
        REG_USERID, USEYN
    )
    VALUES (
        SEQ_REQ_INFO.NEXTVAL, P_PARENTID, P_TITLE, P_CONTENTS_HTML, P_REQDATE, P_DUEDATE, P_EXPECTDATE, P_STARTDATE, P_ENDDATE,
        P_REQTYPE, P_SYSTEMCD, P_REQMENU, P_REQMENU_ETC, P_REQTCODE, P_BXTID, P_REQUSERID, P_RESUSERID,
        P_IMPTCD, P_DFCLTCD, P_PRIORITYCD, P_MAN_DAY, P_PROC_STATUS, P_PROC_RATE, P_CORCD, P_DEPTCD, P_OFFICECD, P_TEAMCD,
        P_REG_USERID, 'Y'
    )
    RETURNING REQID INTO P_NEW_REQID;
END;
/
