

-- TB_ADMIN_REL Table (조치자별 담당시스템)
CREATE TABLE TB_ADMIN_REL (
    ID              NUMBER          NOT NULL,
    USERID          VARCHAR2(10)    NOT NULL,
    MENUS          VARCHAR2(50)    NOT NULL,    
    REG_DATE        DATE            DEFAULT SYSDATE NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    CONSTRAINT PK_TB_ADMIN_REL PRIMARY KEY (ID)
);

COMMENT ON TABLE TB_ADMIN_REL IS '조치자별 담당시스템';

COMMENT ON COLUMN TB_ADMIN_REL.ID IS 'ID';
COMMENT ON COLUMN TB_ADMIN_REL.USERID IS '관리자 ID';
COMMENT ON COLUMN TB_ADMIN_REL.MENUS IS '메뉴 ID';
COMMENT ON COLUMN TB_ADMIN_REL.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_ADMIN_REL.REG_USERID IS '등록자 ID';

-- Sequence for TB_ADMIN_REL ID
CREATE SEQUENCE SEQ_ADMIN_REL
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;