CREATE TABLE TB_COMM_CODE (
    CODEID VARCHAR2(10) NOT NULL,
    PARENTCODEID VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    VALUE NUMBER,
    DEPTH VARCHAR2(1000),
    SORT_ORDER NUMBER,
    NOTE VARCHAR2(1000),
    USEYN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    REG_USERID VARCHAR2(10) NOT NULL,
    UPDATE_DATE DATE,
    UPDATE_USERID VARCHAR2(10),
    CONSTRAINT PK_TB_COMM_CODE PRIMARY KEY (CODEID)
);

COMMENT ON TABLE TB_COMM_CODE IS '공통 코드 관리 테이블';
COMMENT ON COLUMN TB_COMM_CODE.CODEID IS '코드ID';
COMMENT ON COLUMN TB_COMM_CODE.PARENTCODEID IS '부모코드 ID';
COMMENT ON COLUMN TB_COMM_CODE.NAME IS '이름';
COMMENT ON COLUMN TB_COMM_CODE.VALUE IS '값';
COMMENT ON COLUMN TB_COMM_CODE.DEPTH IS '단계';
COMMENT ON COLUMN TB_COMM_CODE.SORT_ORDER IS '정렬순서';
COMMENT ON COLUMN TB_COMM_CODE.NOTE IS '설명';
COMMENT ON COLUMN TB_COMM_CODE.USEYN IS '사용여부';
COMMENT ON COLUMN TB_COMM_CODE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_COMM_CODE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_COMM_CODE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_COMM_CODE.UPDATE_USERID IS '수정자 ID';
