-- TB_COMM_CODE Table (공통 코드 관리 테이블)
CREATE TABLE TB_COMM_CODE (
    CODEID          NUMBER          NOT NULL,
    PARENTID        NUMBER          NOT NULL,
    CODENM          VARCHAR2(20)    NOT NULL,
    CODE            VARCHAR2(10),
    SORTORDER       NUMBER,
    NOTE            VARCHAR2(1000),
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    UPDATE_DATE     DATE,
    UPDATE_USERID   VARCHAR2(10),
    CONSTRAINT PK_TB_COMM_CODE PRIMARY KEY (CODEID)
);

COMMENT ON TABLE TB_COMM_CODE IS '기준정보 테이블';

COMMENT ON COLUMN TB_COMM_CODE.CODEID IS '코드 ID';
COMMENT ON COLUMN TB_COMM_CODE.PARENTID IS '부모코드 ID';
COMMENT ON COLUMN TB_COMM_CODE.CODENM IS '이름';
COMMENT ON COLUMN TB_COMM_CODE.CODE IS '코드';
COMMENT ON COLUMN TB_COMM_CODE.SORTORDER IS '정렬순서';
COMMENT ON COLUMN TB_COMM_CODE.NOTE IS '설명';
COMMENT ON COLUMN TB_COMM_CODE.USEYN IS '사용여부';
COMMENT ON COLUMN TB_COMM_CODE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_COMM_CODE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_COMM_CODE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_COMM_CODE.UPDATE_USERID IS '수정자 ID';

-- Sequence for the primary key
CREATE SEQUENCE SEQ_TB_COMM_CODE
START WITH 1
INCREMENT BY 1;

-- Trigger for the primary key
CREATE OR REPLACE TRIGGER TRG_TB_COMM_CODE_PK
BEFORE INSERT ON TB_COMM_CODE
FOR EACH ROW
BEGIN
    IF :NEW.CODEID IS NULL THEN
        SELECT SEQ_TB_COMM_CODE.NEXTVAL
        INTO :NEW.CODEID
        FROM DUAL;
    END IF;
END;
/