-- TB_DEPT_INFO Table (부서정보 테이블)
CREATE TABLE TB_DEPT_INFO (
    DEPTID      NUMBER          NOT NULL,
    DEPTCD      VARCHAR2(10)    
    PARENTID    NUMBER          
    DEPTNAME    VARCHAR2(100)   NOT NULL,
    CORCD       VARCHAR2(10)    NOT NULL,
    SORTORDER     NUMBER,
    NOTE        VARCHAR2(1000),
    USEYN       VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_DEPT_INFO PRIMARY KEY (DEPTID)
);

COMMENT ON TABLE TB_DEPT_INFO IS '부서정보 테이블';

COMMENT ON COLUMN TB_DEPT_INFO.DEPTID IS '부서ID';
COMMENT ON COLUMN TB_DEPT_INFO.PARENTID IS '상위부서 ID';
COMMENT ON COLUMN TB_DEPT_INFO.DEPTCD IS '부서코드';
COMMENT ON COLUMN TB_DEPT_INFO.DEPTNAME IS '부서명';
COMMENT ON COLUMN TB_DEPT_INFO.CORCD IS '법인코드';
COMMENT ON COLUMN TB_DEPT_INFO.SORTORDER IS '정렬순서';
COMMENT ON COLUMN TB_DEPT_INFO.NOTE IS '설명';
COMMENT ON COLUMN TB_DEPT_INFO.USEYN IS '사용여부';