CREATE TABLE TB_GROUP_INFO (
    GROUPID NUMBER NOT NULL,
    SYSTEMCODE VARCHAR2(20),
    GROUPNAME VARCHAR2(50),
    GROUPNOTE VARCHAR2(2000),
    CONSTRAINT PK_TB_GROUP_INFO PRIMARY KEY (GROUPID)
);

COMMENT ON TABLE TB_GROUP_INFO IS 'GROUP 정보';
COMMENT ON COLUMN TB_GROUP_INFO.GROUPID IS '그룹 ID';
COMMENT ON COLUMN TB_GROUP_INFO.SYSTEMCODE IS '시스템 코드';
COMMENT ON COLUMN TB_GROUP_INFO.GROUPNAME IS '그룹 이름';
COMMENT ON COLUMN TB_GROUP_INFO.GROUPNOTE IS '그룹 설명';
