-- TB_MENU_INFO Table (MENU 정보)
CREATE TABLE TB_MENU_INFO (
    MENUID          VARCHAR2(40)    NOT NULL,
    SYSTEMCODE      VARCHAR2(10)    DEFAULT 'CSR' NOT NULL,
    MENUNAME        VARCHAR2(100)   NOT NULL,
    CONTROLLER      VARCHAR2(20),
    ACTION          VARCHAR2(20),
    URL             VARCHAR2(300),
    PARENTID        VARCHAR2(40), -- Made nullable for root items
    INFO            VARCHAR2(1000),
    SORTORDER         NUMBER,
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    UPDATE_DATE     DATE,
    UPDATE_USERID   VARCHAR2(10),
    CONSTRAINT PK_TB_MENU_INFO PRIMARY KEY (MENUID)
);

COMMENT ON TABLE TB_MENU_INFO IS 'MENU 정보 테이블';

COMMENT ON COLUMN TB_MENU_INFO.MENUID IS '메뉴 ID';
COMMENT ON COLUMN TB_MENU_INFO.SYSTEMCODE IS '시스템 코드';
COMMENT on COLUMN TB_MENU_INFO.MENUNAME IS '메뉴 이름';
COMMENT ON COLUMN TB_MENU_INFO.CONTROLLER IS '메뉴 컨트롤러';
COMMENT ON COLUMN TB_MENU_INFO.ACTION IS '메뉴 행동';
COMMENT ON COLUMN TB_MENU_INFO.URL IS '메뉴 경로';
COMMENT ON COLUMN TB_MENU_INFO.PARENTID IS '상위 메뉴 ID';
COMMENT ON COLUMN TB_MENU_INFO.INFO IS '메뉴정보';
COMMENT ON COLUMN TB_MENU_INFO.SORTORDER IS '메뉴 정렬 순서';
COMMENT ON COLUMN TB_MENU_INFO.USEYN IS '사용 여부';
COMMENT ON COLUMN TB_MENU_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_INFO.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_MENU_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_MENU_INFO.UPDATE_USERID IS '수정자 ID';