-- TB_NOTICE Table (공지사항 테이블)
CREATE TABLE TB_NOTICE (
    ID              NUMBER          NOT NULL,
    TITLE           VARCHAR2(50)    NOT NULL,
    CONTENTS_HTML   CLOB,
    CONTENTS_TEXT   CLOB,
    NOTICETYPE      VARCHAR2(10)    NOT NULL,
    CORCD           VARCHAR2(10)    NOT NULL,
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    UPDATE_DATE     DATE,
    UPDATE_USERID   VARCHAR2(10),
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_NOTICE PRIMARY KEY (ID)
);

COMMENT ON TABLE TB_NOTICE IS '공지사항 테이블';

COMMENT ON COLUMN TB_NOTICE.ID IS 'ID';
COMMENT ON COLUMN TB_NOTICE.TITLE IS '제목';
COMMENT ON COLUMN TB_NOTICE.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN TB_NOTICE.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN TB_NOTICE.NOTICETYPE IS '공지 유형';
COMMENT ON COLUMN TB_NOTICE.CORCD IS '법인코드';
COMMENT ON COLUMN TB_NOTICE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_NOTICE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_NOTICE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_NOTICE.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN TB_NOTICE.USEYN IS '삭제여부';

-- Sequence for the primary key
CREATE SEQUENCE SEQ_NOTICE
START WITH 1
INCREMENT BY 1;

-- Trigger for the primary key
CREATE OR REPLACE TRIGGER TRG_TB_NOTICE_PK
BEFORE INSERT ON TB_NOTICE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_TB_NOTICE.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/
