CREATE TABLE TB_REQ_FILE (
    FILEID NUMBER NOT NULL,
    REQ_ID NUMBER NOT NULL,
    REQ_TYPE VARCHAR2(1) NOT NULL,
    FILE_NAME VARCHAR2(1) NOT NULL,
    FILE_PATH VARCHAR2(1) NOT NULL,
    REG_DATE DATE NOT NULL,
    REG_USERID VARCHAR2(10) NOT NULL,
    USEYN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_FILE PRIMARY KEY (FILEID)
);

COMMENT ON TABLE TB_REQ_FILE IS '요청사항 첨부파일 테이블';
COMMENT ON COLUMN TB_REQ_FILE.FILEID IS '파일 ID';
COMMENT ON COLUMN TB_REQ_FILE.REQ_ID IS '요청글 ID';
COMMENT ON COLUMN TB_REQ_FILE.REQ_TYPE IS '첨부파일 구분';
COMMENT ON COLUMN TB_REQ_FILE.FILE_NAME IS '파일명';
COMMENT ON COLUMN TB_REQ_FILE.FILE_PATH IS '파일 경로';
COMMENT ON COLUMN TB_REQ_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REQ_FILE.REG_USERID IS '등록자ID';
COMMENT ON COLUMN TB_REQ_FILE.USEYN IS '사용여부';
