-- TB_REQ_INFO Table (요청사항 관리)
CREATE TABLE TB_REQ_INFO (
    REQID           NUMBER          NOT NULL,
    PARENTID        NUMBER,
    TITLE           VARCHAR2(50)    NOT NULL,
    CONTENTS_HTML   CLOB,
    CONTENTS_TEXT   CLOB,
    REQDATE         DATE            NOT NULL,
    DUEDATE         DATE,
    EXPECTDATE      DATE            NOT NULL,
    STARTDATE       DATE            NOT NULL,
    ENDDATE         DATE            NOT NULL,
    REQTYPE         VARCHAR2(10)    NOT NULL,
    SYSTEMCD        VARCHAR2(10)    NOT NULL,
    REQMENU         VARCHAR2(10),
    REQMENU_ETC     VARCHAR2(100),
    REQTCODE        VARCHAR2(10),
    RESTCODE        VARCHAR2(10),
    BXTID           VARCHAR2(10),
    REQUSERID       VARCHAR2(10)    NOT NULL,
    RESUSERID       VARCHAR2(10),
    IMPTCD          VARCHAR2(10),
    DFCLTCD         VARCHAR2(10),
    PRIORITYCD      VARCHAR2(10)    NOT NULL,
    MAN_DAY         FLOAT,
    PROC_STATUS     VARCHAR2(10),
    PROC_RATE       NUMBER,
    ANSWER_HTML     CLOB,
    ANSWER_TEXT     CLOB,
    DELAYREASON_HTML CLOB,
    DELAYREASON_TEXT CLOB,
    CORCD           VARCHAR2(10)    NOT NULL,
    DEPTCD          VARCHAR2(10)    NOT NULL,
    OFFICECD        VARCHAR2(10)    NOT NULL,
    TEAMCD          VARCHAR2(10)    NOT NULL,
    NOTE_HTML       CLOB,
    NOTE_TEXT       CLOB,
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    UPDATE_DATE     DATE,
    UPDATE_USERID   VARCHAR2(10),
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_INFO PRIMARY KEY (REQID)
);

COMMENT ON TABLE TB_REQ_INFO IS '요청사항 관리 테이블';

COMMENT ON COLUMN TB_REQ_INFO.REQID IS '요청번호';
COMMENT ON COLUMN TB_REQ_INFO.PARENTID IS '상위요청그룹번호';
COMMENT ON COLUMN TB_REQ_INFO.TITLE IS '제목';
COMMENT ON COLUMN TB_REQ_INFO.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN TB_REQ_INFO.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN TB_REQ_INFO.REQDATE IS '요청일';
COMMENT ON COLUMN TB_REQ_INFO.DUEDATE IS '처리기한';
COMMENT ON COLUMN TB_REQ_INFO.EXPECTDATE IS '완료예정일';
COMMENT ON COLUMN TB_REQ_INFO.STARTDATE IS '실제 시작일';
COMMENT ON COLUMN TB_REQ_INFO.ENDDATE IS '실제 종료일';
COMMENT ON COLUMN TB_REQ_INFO.REQTYPE IS '요청유형';
COMMENT ON COLUMN TB_REQ_INFO.SYSTEMCD IS '대상시스템';
COMMENT ON COLUMN TB_REQ_INFO.REQMENU IS '요청메뉴(영역)';
COMMENT ON COLUMN TB_REQ_INFO.REQMENU_ETC IS '기타메뉴';
COMMENT ON COLUMN TB_REQ_INFO.BXTID IS 'BXT문의번호';
COMMENT ON COLUMN TB_REQ_INFO.REQTCODE IS '요청자 t-code';
COMMENT ON COLUMN TB_REQ_INFO.RESTCODE IS '조치자 t-code';
COMMENT ON COLUMN TB_REQ_INFO.REQUSERID IS '요청자';
COMMENT ON COLUMN TB_REQ_INFO.RESUSERID IS '조치자';
COMMENT ON COLUMN TB_REQ_INFO.IMPTCD IS '중요도';
COMMENT ON COLUMN TB_REQ_INFO.DFCLTCD IS '난이도';
COMMENT ON COLUMN TB_REQ_INFO.PRIORITYCD IS '긴급도';
COMMENT ON COLUMN TB_REQ_INFO.MAN_DAY IS '투입공수';
COMMENT ON COLUMN TB_REQ_INFO.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN TB_REQ_INFO.PROC_RATE IS '진행률';
COMMENT ON COLUMN TB_REQ_INFO.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN TB_REQ_INFO.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN TB_REQ_INFO.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN TB_REQ_INFO.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN TB_REQ_INFO.CORCD IS '법인코드';
COMMENT ON COLUMN TB_REQ_INFO.DEPTCD IS '부서코드';
COMMENT ON COLUMN TB_REQ_INFO.OFFICECD IS '실 코드';
COMMENT ON COLUMN TB_REQ_INFO.TEAMCD IS '팀 코드';
COMMENT ON COLUMN TB_REQ_INFO.NOTE_HTML IS '조치 내역';
COMMENT ON COLUMN TB_REQ_INFO.NOTE_TEXT IS '조치 내역';
COMMENT ON COLUMN TB_REQ_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REQ_INFO.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_REQ_INFO.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TB_REQ_INFO.UPDATE_USERID IS '수정자 ID';
COMMENT ON COLUMN TB_REQ_INFO.USEYN IS '삭제여부';

-- Sequence for the primary key
CREATE SEQUENCE SEQ_TB_REQ_INFO
START WITH 1
INCREMENT BY 1;

-- Trigger for the primary key
CREATE OR REPLACE TRIGGER TRG_TB_REQ_INFO_PK
BEFORE INSERT ON TB_REQ_INFO
FOR EACH ROW
BEGIN
    IF :NEW.REQID IS NULL THEN
        SELECT SEQ_TB_REQ_INFO.NEXTVAL
        INTO :NEW.REQID
        FROM DUAL;
    END IF;
END;
/
