-- TB_REQ_HIST Table (요청사항 히스토리)
CREATE TABLE TB_REQ_HIST (
    HISTORYID       NUMBER          NOT NULL,
    REQID           NUMBER          NOT NULL,
    PARENTID        NUMBER,
    TITLE           VARCHAR2(50)    NOT NULL,
    CONTENTS_HTML   CLOB,
    CONTENTS_TEXT   CLOB,
    REQDATE         DATE            NOT NULL,
    DUEDATE         DATE,
    EXPECTDATE      DATE            NOT NULL,
    STARTDATE       DATE            NOT NULL,
    ENDDATE         DATE            NOT NULL,
    REQTYPE         VARCHAR2(10)    NOT NULL,
    SYSTEMCD        VARCHAR2(10)    NOT NULL,
    REQMENU         VARCHAR2(10),
    REQUSERID       VARCHAR2(10)    NOT NULL,
    RESUSERID       VARCHAR2(10),
    DFCLTCD         VARCHAR2(10),
    PRIORITYCD      VARCHAR2(10)    NOT NULL,
    MAN_DAY         FLOAT,
    PROC_STATUS     VARCHAR2(10),
    PROC_RATE       NUMBER,
    ANSWER_HTML     CLOB,
    ANSWER_TEXT     CLOB,
    DELAYREASON_HTML CLOB,
    DELAYREASON_TEXT CLOB,
    CORCD           VARCHAR2(10)    NOT NULL,
    DEPTCD          VARCHAR2(10)    NOT NULL,
    OFFICECD        VARCHAR2(10)    NOT NULL,
    TEAMCD          VARCHAR2(10)    NOT NULL,
    REQHISTORY      VARCHAR2(1000),
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_HIST PRIMARY KEY (HISTORYID)
);

COMMENT ON TABLE TB_REQ_HIST IS '요청사항 히스토리 테이블';

COMMENT ON COLUMN TB_REQ_HIST.HISTORYID IS '히스토리번호';
COMMENT ON COLUMN TB_REQ_HIST.REQID IS '요청번호';
COMMENT ON COLUMN TB_REQ_HIST.PARENTID IS '상위요청번호';
COMMENT ON COLUMN TB_REQ_HIST.TITLE IS '제목';
COMMENT ON COLUMN TB_REQ_HIST.CONTENTS_HTML IS '내용(HTML)';
COMMENT ON COLUMN TB_REQ_HIST.CONTENTS_TEXT IS '내용(TEXT)';
COMMENT ON COLUMN TB_REQ_HIST.REQDATE IS '요청일';
COMMENT ON COLUMN TB_REQ_HIST.DUEDATE IS '처리기한';
COMMENT ON COLUMN TB_REQ_HIST.EXPECTDATE IS '완료예정일';
COMMENT ON COLUMN TB_REQ_HIST.STARTDATE IS '실제 시작일';
COMMENT ON COLUMN TB_REQ_HIST.ENDDATE IS '실제 종료일';
COMMENT ON COLUMN TB_REQ_HIST.REQTYPE IS '요청유형';
COMMENT ON COLUMN TB_REQ_HIST.SYSTEMCD IS '대상시스템';
COMMENT ON COLUMN TB_REQ_HIST.REQMENU IS '요청메뉴(영역)';
COMMENT ON COLUMN TB_REQ_HIST.REQUSERID IS '요청자';
COMMENT ON COLUMN TB_REQ_HIST.RESUSERID IS '조치자';
COMMENT ON COLUMN TB_REQ_HIST.DFCLTCD IS '난이도';
COMMENT ON COLUMN TB_REQ_HIST.PRIORITYCD IS '긴급도';
COMMENT ON COLUMN TB_REQ_HIST.MAN_DAY IS '투입공수';
COMMENT ON COLUMN TB_REQ_HIST.PROC_STATUS IS '진행상태';
COMMENT ON COLUMN TB_REQ_HIST.PROC_RATE IS '진행률';
COMMENT ON COLUMN TB_REQ_HIST.ANSWER_HTML IS '답변내용 html';
COMMENT ON COLUMN TB_REQ_HIST.ANSWER_TEXT IS '답변내용 text';
COMMENT ON COLUMN TB_REQ_HIST.DELAYREASON_HTML IS '지연사유 html';
COMMENT ON COLUMN TB_REQ_HIST.DELAYREASON_TEXT IS '지연사유 text';
COMMENT ON COLUMN TB_REQ_HIST.CORCD IS '법인코드';
COMMENT ON COLUMN TB_REQ_HIST.DEPTCD IS '부서코드';
COMMENT ON COLUMN TB_REQ_HIST.OFFICECD IS '실 코드';
COMMENT ON COLUMN TB_REQ_HIST.TEAMCD IS '팀 코드';
COMMENT ON COLUMN TB_REQ_HIST.REQHISTORY IS '조치내역(히스토리)';
COMMENT ON COLUMN TB_REQ_HIST.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REQ_HIST.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_REQ_HIST.USEYN IS '삭제여부';