-- TB_REQ_FILE Table (요청사항 첨부파일 테이블)
CREATE TABLE TB_REQ_FILE (
    FILEID          NUMBER          NOT NULL,
    REQID           NUMBER          NOT NULL,
    HISTORYID       NUMBER          NOT NULL,
    REQTYPE         VARCHAR2(1)     NOT NULL,
    UPLOAD_FILENAME VARCHAR2(64)    NOT NULL,
    REAL_FILENAME   VARCHAR2(50)    NOT NULL,
    FILEPATH        VARCHAR2(100)   NOT NULL,
    REG_DATE        DATE            DEFAULT sysdate NOT NULL,
    REG_USERID      VARCHAR2(10)    NOT NULL,
    USEYN           VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_REQ_FILE PRIMARY KEY (FILEID)
);

COMMENT ON TABLE TB_REQ_FILE IS '요청사항 첨부파일 테이블';

COMMENT ON COLUMN TB_REQ_FILE.FILEID IS '파일 ID';
COMMENT ON COLUMN TB_REQ_FILE.REQID IS '요청글 ID';
COMMENT ON COLUMN TB_REQ_FILE.HISTORYID IS '히스토리 ID';
COMMENT ON COLUMN TB_REQ_FILE.REQTYPE IS '첨부파일 구분';
COMMENT ON COLUMN TB_REQ_FILE.UPLOAD_FILENAME IS '서버에 저장하는 파일 명 ( 해시값 or 타입스탬프 기반 이름 )';
COMMENT ON COLUMN TB_REQ_FILE.REAL_FILENAME IS '파일명';
COMMENT ON COLUMN TB_REQ_FILE.FILEPATH IS '파일 저장 경로';
COMMENT ON COLUMN TB_REQ_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REQ_FILE.REG_USERID IS '등록자 ID';
COMMENT ON COLUMN TB_REQ_FILE.USEYN IS '사용여부';

-- Sequence for the primary key
CREATE SEQUENCE SEQ_TB_REQ_FILE
START WITH 1
INCREMENT BY 1;

-- Trigger for the primary key
CREATE OR REPLACE TRIGGER TRG_TB_REQ_FILE_PK
BEFORE INSERT ON TB_REQ_FILE
FOR EACH ROW
BEGIN
    IF :NEW.FILEID IS NULL THEN
        SELECT SEQ_TB_REQ_FILE.NEXTVAL
        INTO :NEW.FILEID
        FROM DUAL;
    END IF;
END;
/