-- TB_TEAM_INFO Table (팀 정보 테이블)
CREATE TABLE TB_TEAM_INFO (
    TEAMCD      VARCHAR2(10)    NOT NULL,
    TEAMNAME    VARCHAR2(100)   NOT NULL,
    DEPTCD      VARCHAR2(10)    NOT NULL,
    SORTORDER     NUMBER,
    NOTE        VARCHAR2(1000),
    USEYN       VARCHAR2(1)     DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_TB_TEAM_INFO PRIMARY KEY (TEAMCD)
);

COMMENT ON TABLE TB_TEAM_INFO IS '팀 정보 테이블';

COMMENT ON COLUMN TB_TEAM_INFO.TEAMCD IS '팀코드';
COMMENT ON COLUMN TB_TEAM_INFO.TEAMNAME IS '팀명';
COMMENT ON COLUMN TB_TEAM_INFO.DEPTCD IS '부서코드';
COMMENT ON COLUMN TB_TEAM_INFO.SORTORDER IS '정렬순서';
COMMENT ON COLUMN TB_TEAM_INFO.NOTE IS '설명';
COMMENT ON COLUMN TB_TEAM_INFO.USEYN IS '사용여부';